#! /usr/bin/env bash

apt-get update

apt-get install -y \
  git \
  build-essential \
  libssl-dev \
  make \
  libreadline6-dev \
  zlib1g-dev \
  libyaml-dev \
  libpq-dev \
  libxslt1-dev \
  libxml2-dev \
  nodejs \
  npm \
  postgresql-9.3 \
  postgresql-contrib-9.3

# Some versions of ubuntu have a legacy program called node. 
# We want node to refer to nodejs
ln -sf /usr/bin/nodejs /usr/bin/node
